name: Build and upload

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: ${{ matrix.platform.name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: 'Windows (x64)', os: windows-latest }
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROSS_COMPILE_ARCH: ${{ matrix.platform.arch }}
        run: npm run release